create table label
(
    id   int generated by default as identity primary key,
    name varchar(50) not null
);

create table post
(
    id      int generated by default as identity primary key,
    content varchar(255),
    created timestamp   not null,
    updated timestamp   not null,
    status  varchar(25) not null
);

create table writer
(
    id        int generated by default as identity primary key,
    firstName varchar(25),
    lastName  varchar(20)
);

create table label_post
(
    post_id  int,
    foreign key (post_id) references post (id),
    label_id int,
    foreign key (label_id) references label (id) on delete set null
);

create table writer_post
(
    writer_id int,
    foreign key (writer_id) references writer (id),
    posts_id  int,
    foreign key (posts_id) references post (id)
);